### ISSUE TITLE
git hub actions is giving me an error

### ISSUE THREAD

**Issue by Fisseha-Estifanos** [iterative/example_cml#217]
![image](https://user-images.githubusercontent.com/74893977/169697627-aae395de-c0e7-493d-bd3a-ddd4fae4d322.png)

{"code":"ENOENT","errno":-2,"level":"error","message":"ENOENT: no such file or directory, stat 'plot.png'","path":"plot.png","stack":"Error: ENOENT: no such file or directory, stat 'plot.png'","syscall":"stat"}
Error: Process completed with exit code 1.

I'm having this error when I'm pushing the repo I forked, I added the code you guys gave me into cml.yml. And when git hub actions is running the trani.py part of the cml.yml file the above error is occurring. Please help, I really want to start using this cml thing.

**Comment by casperdcl** [comment]
Ah that's a bug introduced in #171, sorry. In your `train.py`, can you change `confusion_matrix.png` to `plot.png`?

**Comment by Fisseha-Estifanos** [comment]
@casperdcl thanks, man, you got the error right. Everything Is fixed now.
